text_file = open("students4.txt", "wt")
text_file.write("Авдеєва Серафима, 2 \n")
text_file.write("Хоренко Павло, 7.4 \n")
text_file.write("Векслер Поліна, 9 \n")
text_file.write("Заригіна Анна, 1.5 \n")
text_file.write("Кучеренко Діанна, 5 \n")
text_file.write("Баранюк Андрій, 1 \n")
text_file.write("Шайда Віталій, 7.5 \n")
text_file.write("Рябчун Анастасія, 9.3 \n")
text_file.write("Бурцев Максим, 2.5 \n")
text_file.write("Дементьева Анжелика, 8.1 \n")
text_file.close()

text_file = open("students5.txt", "wt")
text_file.write("Зеленюк Дарина, 1.3 \n")
text_file.write("Литвин Анастасія, 4.5 \n")
text_file.write("Люлька Вікторія, 7 \n")
text_file.write("Білянський Олександр, 3 \n")
text_file.write("Шепітько Ярослава, 3.9 \n")
text_file.write("Скрипка Твердислава, 8.9 \n")
text_file.write("Семененко Чеслава, 3 \n")
text_file.close()

text_file = open("students6.txt", "wt")
text_file.write("Андрушків Йосипа, 5.8 \n")
text_file.write("Колосюк Христя, 4 \n")
text_file.write("Хрієнко Цецілія, 7.6 \n")
text_file.write("Колцуняк Іванна,, 8.2 \n")
text_file.write("Грушкевич Іларія, 9 \n")
text_file.write("Федак Віра, 2 \n")
text_file.write("Гречаник Емілія, 1 \n")
text_file.close()